# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6fa0ed9bb00cb3eacb0012fdfeefa56493f118bb5ad9655c5a097156bd8d68b36c7a5c9a135067c82e2e0af117b773cb1043ee8a381c48d2dff1fb94e9600ca

test:
  secret_key_base: 76f588bf01d5a19ddac6c2cca4f0c9b65aa018b83836524101e5f719d98c67db30c1a080ec49fc35b18478191730401c5ccd01be203ac50cf264f2164004d53f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
